// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Website.Data;

#nullable disable

namespace Website.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260104211535_Change_Ride_Table")]
    partial class Change_Ride_Table
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.1");

            modelBuilder.Entity("Website.Models.Ride", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("ElevationGain")
                        .HasColumnType("REAL");

                    b.Property<double>("ElevationLoss")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("End")
                        .HasColumnType("TEXT");

                    b.Property<int>("FastAccelerationCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FastDecelerationCount")
                        .HasColumnType("INTEGER");

                    b.Property<double>("MaxSpeed")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("Start")
                        .HasColumnType("TEXT");

                    b.Property<int>("TrackPointCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Rides");
                });

            modelBuilder.Entity("Website.Models.TrackPoint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Elevation")
                        .HasColumnType("REAL");

                    b.Property<double>("Hdop")
                        .HasColumnType("REAL");

                    b.Property<double>("Latitude")
                        .HasColumnType("REAL");

                    b.Property<double>("Longitude")
                        .HasColumnType("REAL");

                    b.Property<int>("RideId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Speed")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("Time")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RideId");

                    b.ToTable("TrackPoints");
                });

            modelBuilder.Entity("Website.Models.TrackPoint", b =>
                {
                    b.HasOne("Website.Models.Ride", null)
                        .WithMany("TrackPoints")
                        .HasForeignKey("RideId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Website.Models.Ride", b =>
                {
                    b.Navigation("TrackPoints");
                });
#pragma warning restore 612, 618
        }
    }
}
